package com.example.us.Message;

//MSG 타입
public enum MessageType {
	CONNECT,DISCONNECT,
	MSG,QUERY,SUCCESS,FAIL,
	USERLIST,NOTIFICATION,CHANGE,
	ROOMLIST,CREATEROOM,INVITE,OUT,
	IMG,VIDEO,MSG_LIST
}
